#### crowsnest.conf
#### This is the default config after installation.
#### It is also used as the default config in MainsailOS.
#### For details on how to configure this to your needs, see:
#### https://github.com/mainsail-crew/crowsnest/blob/master/README.md


#####################################################################
####                                                            #####
####      Information about ports and according URL's           #####
####                                                            #####
#####################################################################
####                                                            #####
####    Port 8080 equals /webcam/?action=[stream/snapshot]      #####
####    Port 8081 equals /webcam2/?action=[stream/snapshot]     #####
####    Port 8082 equals /webcam3/?action=[stream/snapshot]     #####
####    Port 8083 equals /webcam4/?action=[stream/snapshot]     #####
####                                                            #####
####    Note: These ports are default for most Mainsail         #####
####    installations. Using any other port would involve       #####
####    changing the proxy configuration or using URLs          #####
####    with the specific port like                             #####
####    http://<ip>:<port>/?action=[stream/snapshot]            #####
####                                                            #####
#####################################################################
####    RTSP Stream URL: ( if enabled and supported )           #####
####    rtsp://<ip>:<rtsp_port>/stream.h264                     #####
#####################################################################


[crowsnest]
log_path: /home/voronpi/printer_data/logs/crowsnest.log
log_level: verbose                      # Valid Options are quiet/verbose/debug
delete_log: true                       # Deletes log on every restart, if set to true
no_proxy: true                         # If set to true, no reverse proxy is required. Only change this, if you know what you are doing.

# [cam c920]
# mode: camera-streamer
# port: 8080
# device: /dev/v4l/by-id/usb-046d_HD_Pro_Webcam_C920_F6F2519F-video-index0
# resolution: 1280x720
# max_fps: 30
# custom_flags: 
#     --camera-format=MJPEG
#     --camera-force_active=1
# v4l2ctl: v4l2ctl: brightness=128, contrast=160, saturation=150, sharpness=170, gain=80, backlight_compensation=1, power_line_frequency=2, white_balance_automatic=1, auto_exposure=3, exposure_dynamic_framerate=0, focus_automatic_continuous=0, focus_absolute=45, zoom_absolute=100, pan_absolute=0, tilt_absolute=0


[cam brio]
mode: camera-streamer
port: 8080
device: /dev/v4l/by-id/usb-046d_Logitech_BRIO_41007229-video-index0
resolution: 1280x720
max_fps: 30
custom_flags: 
    --camera-format=MJPEG
    --camera-force_active=1

v4l2ctl: brightness=128, contrast=160, saturation=150, sharpness=170, gain=80, backlight_compensation=1, power_line_frequency=2, white_balance_automatic=1, auto_exposure=3, exposure_dynamic_framerate=0, focus_automatic_continuous=0, focus_absolute=15, zoom_absolute=175, pan_absolute=0, tilt_absolute=0

#  horizontal_flip=1,vertical_flip=1, 